### PR TITLE
settings page

### PR DESCRIPTION
**Pull request by sanketshevare**
## Code of Conduct
- [ ] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 
- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/QHBPq6xP5p) community. 
Feel free to check out other cool repositories of the [Thecyberworld](https://github.com/thecyberworld). 
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Review by kabir0x23 — CHANGES_REQUESTED** [review]
Hey

you have to copy the pack-age.json file from our repositry  and paste that same code in the package-lock.json in your same branch 

and push the code 
we should  not do git add . or *
image

**Review by kabir0x23 — APPROVED** [review]

**Comment by sanketshevare** [comment]
Okay

**Comment by sanketshevare** [comment]
Need to do it again?

**Comment by kabir0x23** [comment]
THanks for contributing to this project

**Comment by sanketshevare** [comment]
> nope, i have fixed it my self

Ohh thanks

**Pull request merged**
