### PR TITLE
Add app icons and splash image.

### LINKED ISSUE #8: [FEATURE] Add Splash Screen and App Logo
### Detailed description

the App schould have a proper splash screen and logo added

### Context

basic setup

### Possible implementation

using the cyberworld logo

### Additional information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ATH42**
Closes #8 

## Code of Conduct
- [x] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 
- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/QHBPq6xP5p) community. 
Feel free to check out other cool repositories of the [Thecyberworld](https://github.com/thecyberworld). 
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Comment by kabir0x23** [comment]
@ATH42 is this PR is completed or 
you are working on this?

**Comment by ATH42** [comment]
It's ready to launch.

**Comment by kabir0x23** [comment]
> It's ready to launch.

on my end, this is how it looks, only for 1 sec, then the homepage opens.

Screenshot_2022-10-05-16-20-25-94_f73b71075b1de7323614b647fe394240

**Comment by ATH42** [comment]
this seems weird. leave the PR open please, i will get to it as soon as i can.

**Comment by kabir0x23** [comment]
> this seems weird. leave the PR open please, i will get to it as soon as i can.

Okay.

**Comment by ATH42** [comment]
the background should also be dark.

**Comment by kabir0x23** [comment]
> the background should also be dark.

yes. and wait i am sending you the new logo

**Comment by kabir0x23** [comment]
Yes dark bg
at the bottom:
- by thecyberworld community
- or thecyberworld community
You can use any one logo
thecyberworld-green
thecyberworld-green01

**Review by kabir0x23 — APPROVED** [review]
Awesome

**Pull request merged**
