### PR TITLE
[FEATURE for Developers] Add And Configure ESlint and Prettier

### LINKED ISSUE #77: [FEATURE for Developers] Configure ESlint and Prettier
### Detailed description

Need to configure ESlint and Prettier as in the "TheCyberHUB" project , for better development experience

### Context

I noticed that in some parts the indentation is not readable so we need to configure Prettier to make the same structure for all the developers.
ESlint is to make the developers be persistent under its rules

### Possible implementation

Add the packages and files , can be copied from "TheCyberHUB" or configured from scratch

### Additional information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ArkadiK94**
Why: it is very important to have Eslint for errors and Prettier for code format
How: Add Eslint and Prettier configure and solve bugs that it alerted about
What: Add And Configure ESlint and Prettier

## Fixes Issue

Closes #77

## Changes proposed

configure ESlint and Prettier similar as in the "TheCyberHUB" project , for better development experience
I used a package eslint-config-universe because it is the recommended one from the expo docs
https://docs.expo.dev/guides/using-eslint/

## Screenshots

There has not been made a visual change

## Note to reviewers

The changes in files and some files extension was needed for the ESlint to pass.

## Code of Conduct
- [x] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 
- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation. - I don't know,however I added some styles in package.json
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/QHBPq6xP5p) community. 
Feel free to check out other cool repositories of the [Thecyberworld](https://github.com/thecyberworld). 
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Comment by ArkadiK94** [comment]
@kabir0x23

**Comment by ArkadiK94** [comment]
I am a little bit confused,  you have some files that use typescript so I added to eslint the right configurations. However,  you also have files that don't use typescript. Do you want to use typescript in the project or not? Do you want me to open an issue about this topic? @kabir0x23

**Comment by kabir0x23** [comment]
> I am a little bit confused, you have some files that use typescript so I added to eslint the right configurations. However, you also have files that don't use typescript. Do you want to use typescript in the project or not? Do you want me to open an issue about this topic? @kabir0x23

I think ts is only being used in 1 or 2 components

if we convert the project into the type it will take time...

will think, and u can create issues according to what u think will be better for project

thank you,

**Review by kabir0x23 — COMMENTED** [review]
Thank you for your contributions @ArkadiK94 

Will review and merge it by today.

**Review by kabir0x23 — APPROVED** [review]
Thanks for your contrbutions,

and apllogise for delay.

**Comment by ArkadiK94** [comment]
It is ok. I opened a new issue about typescript, however, in this pr, I changed some files to tsx and I am not sure if I should leave it or change to jsx. Do you want to merge this pr and think about it in the relevant issue?

**Comment by ArkadiK94** [comment]
@kabir0x23 I merge this pr and lets talk about ts in the relevant pr :)

**Comment by kabir0x23** [comment]
> @kabir0x23 Could you merge this pr and we will talk about ts in the relevant pr?

yes sure



Thanks for your contrbutions,

and apllogise for delay again.

**Pull request merged**
